# Generated by Django 5.1 on 2024-08-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinee',
            name='education_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
