# Generated by Django 5.1 on 2024-08-24 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_rename_user_notification_examinee'),
        ('users', '0002_alter_examinee_education_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='for_all',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='examinee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.examinee'),
        ),
    ]
