# Generated by Django 5.1 on 2024-08-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_notification_for_all_alter_notification_examinee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='for_all',
        ),
    ]
